name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Shell Script Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck on scripts
        run: shellcheck Scripts/* Scripts/Setupscripts/* || exit 1

  markdownlint:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run MarkdownLint
        run: markdownlint **/*.md || exit 1
